"""
models.py — Pydantic data models for the FinSight query pipeline.

Using Pydantic here gives us automatic validation and clear field contracts
between the LLM layer, the DB layer, and the summarisation layer, which
makes debugging much easier (bad data fails loudly at the boundary).
"""

from pydantic import BaseModel


class SQLResponse(BaseModel):
    """
    The structured output expected from Gemini.

    Gemini is asked to return JSON with exactly these two fields so the
    result can be validated before the SQL is ever sent to the database.
    """

    sql: str          # A valid SQLite SELECT statement
    explanation: str  # One-sentence description of what the query does


class QueryResult(BaseModel):
    """
    The final, fully-resolved result of a single user question.

    Bundles every artefact produced by the pipeline so callers (dashboards,
    tests, CLI) can access whichever part they need.
    """

    question: str       # The original natural-language question
    sql: str            # The SQL generated by Gemini
    rows: list[dict]    # Raw rows returned from SQLite
    summary: str        # Natural-language answer produced by Groq
